# Generated by Django 5.1.3 on 2025-01-08 21:27

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_task_notification_time_alter_task_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='deadline',
            field=models.DateTimeField(blank=True, null=True, validators=[tasks.models.validate_deadline]),
        ),
        migrations.AlterField(
            model_name='task',
            name='notification_time',
            field=models.PositiveIntegerField(default=24, help_text='Počet hodin před termínem, kdy má být odeslána notifikace.', validators=[tasks.models.validate_notification_time]),
        ),
    ]
