# Generated by Django 5.1.3 on 2025-01-13 19:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_alter_task_deadline_alter_task_notification_time'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Název šablony')),
                ('description', models.TextField(blank=True, verbose_name='Popis šablony')),
                ('repeat_interval', models.CharField(choices=[('none', 'Neopakovat'), ('daily', 'Denně'), ('weekly', 'Měsíčně')], default='none', max_length=20, verbose_name='Interval opakování')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Vytvořeno')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Aktualizováno')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Vytvořil')),
            ],
        ),
    ]
