# Generated by Django 5.1.3 on 2025-01-14 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_alter_template_repeat_interval_subtasktemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtasktemplate',
            name='description',
            field=models.TextField(blank=True, verbose_name='Popis podúkolu'),
        ),
    ]
